# front_camera:
#   ros__parameters:
#     camera:
#       i_mx_id: 18443010C1038C1200
#       i_pipeline_type: RGB
#       i_floodlight_brightness: 200
#       i_laser_dot_brightness: 200
#     nn:
#       i_nn_config_path: depthai_ros_driver/mobilenet
left_camera:
  ros__parameters:
    camera:
      i_mx_id: 18443010C1038C1200
      i_pipeline_type: RGB
      i_floodlight_brightness: 100
      i_laser_dot_brightness: 200
    nn:
      i_nn_config_path: depthai_ros_driver/mobilenet
right_camera:
  ros__parameters:
    camera:
      i_mx_id: 18443010C1038C1200
      i_pipeline_type: RGB
      i_floodlight_brightness: 100
      i_laser_dot_brightness: 200
    nn:
      i_nn_config_path: depthai_ros_driver/mobilenet
